export enum ProblemsActions {
  SET_PROBLEMS = "SET_PROBLEMS",
  LOADING_PROBLEMS = "LOADING_PROBLEMS",
  SET_CURRENT_PAGE = "SET_CURRENT_PAGE",
  SET_CURRENT_PROBLEM = "SET_CURRENT_PROBLEM",
  SET_CURRENT_PROBLEM_COMMENTS = "SET_CURRENT_PROBLEM_COMMENTS",
  SET_CURRENT_PROBLEM_COMMENTS_PAGE = "SET_CURRENT_PROBLEM_COMMENTS_PAGE",
  SET_CURRENT_PROBLEM_SOLUTION_ATTEMPTS = "SET_CURRENT_PROBLEM_SOLUTION_ATTEMPTS",
  SET_CURRENT_PROBLEM_SOLUTION_ATTEMPTS_PAGE = "SET_CURRENT_PROBLEM_SOLUTION_ATTEMPTS_PAGE"
}

export enum TechniquesActions {
  SET_TECHNIQUES = "SET_TECHNIQUES",
  SET_CURRENT_TECHNIQUE = "SET_CURRENT_TECHNIQUE",
  LOADING_TECHNIQUES = "LOADING_TECHNIQUES",
  SET_CURRENT_PAGE = "SET_CURRENT_PAGE"
}

export enum ConceptsActions {
  LOADING_CONCEPTS = "LOADING_CONCEPTS",
  SET_CONCEPTS = "SET_CONCEPTS",
  SET_CURRENT_CONCEPT = "SET_CURRENT_CONCEPT",
  SET_CURRENT_PAGE = "SET_CURRENT_PAGE"
}

export enum SolutionAttemptActions {
  SET_CURRENT_SOLUTION
}
